server:
  port: ${PORT:8085}
spring:
  application:
    name: productservice
  datasource:
    url: jdbc:mysql://localhost:3306/msv_productdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      pricingService:
        register-health-indicator: true # Activa el indicadtor de la salud para monitorear el circuit breaker
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expone todos los endpoints de Actuator
